# Generated by Django 3.0.3 on 2020-02-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='icon',
            field=models.CharField(choices=[('fa-axe-battle', 'Axe'), ('fa-mandolin', 'Lute'), ('fa-shield-cross', 'Shield'), ('fa-paw-claws', 'Paw'), ('fa-swords', 'Swords'), ('fa-fist-raised', 'Fist'), ('fa-helmet-battle', 'Helmet'), ('fa-bow-arrow', 'Bow'), ('fa-dagger', 'Dagger'), ('fa-hand-holding-magic', 'Magic Hand'), ('fa-eye-evil', 'Eye'), ('fa-book-spells', 'Spell Book')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='theme',
            field=models.CharField(choices=[('E7623E', 'Barbarian Fire'), ('AB6DAC', 'Bard Rogue'), ('91A1B2', 'Cleric Silver'), ('7A853B', 'Druid Moss'), ('7F513E', 'Fighter Rust'), ('51A5C5', 'Monk Sky'), ('B59E54', 'Paladin Gold'), ('507F62', 'Ranger Emerald'), ('555752', 'Rogue Ash'), ('992E2E', 'Sorcerer Blood'), ('7B469B', 'Warlock Iris'), ('2A50A1', 'Wizard Cobalt')], default='1', max_length=50),
        ),
    ]
